[workspace]
authors = ["maxidl <maximilian@ellamind.com>"]
channels = ["conda-forge"]
name = "synth-data-examples"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
openai = ">=2.7.1, <3"
pandas = ">=2.3.3, <3"
polars = ">=1.35.1, <2"
datasets = ">=4.4.1, <5"
jupyter = ">=1.1.1, <2"
